on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.5.2"
          host: "linux"
          target: "desktop"
          arch: "gcc_64"
          install-deps: "true"

      - name: List files in Qt
        run: find ${{env.Qt5_Dir}}

      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B '${{github.workspace}}'/build

      - name: Build
        run: cmake --build '${{github.workspace}}'/build

      - name: Download linuxdeployqt
        run: |
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage

      - name: Package artifacts with linuxdeployqt
        run: |
          mkdir -p appdir/usr/bin/
          mv ./build/calculatorbuilder appdir/usr/bin/
          export VERSION=0.0.1-linux # linuxdeployqt uses this for naming the package
          echo "Version is: ${VERSION}"
          ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract-and-run appdir/usr/share/applications/*.desktop \
            -appimage -verbose=2 -extra-plugins=iconengines

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
